version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_USER=telegraph_user
      - DB_HOST=db
      - DB_NAME=telegraph_db
      - DB_PASSWORD=your_secure_password
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - telegraph-network

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=telegraph_user
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=telegraph_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - telegraph-network

networks:
  telegraph-network:
    driver: bridge

volumes:
  postgres_data: