version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - telegraph-network
    pull_policy: if_not_present
  
  db:
    # Используем Bitnami PostgreSQL образ (не требует Docker Hub)
    image: bitnami/postgresql:14
    restart: always
    environment:
      # Явно указываем имя пользователя, пароль и базу данных
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
      # Добавляем пароль суперпользователя
      - POSTGRESQL_POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - telegraph-network
    pull_policy: if_not_present

networks:
  telegraph-network:
    driver: bridge
volumes:
  postgres_data:
