version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - telegraph-network
    pull_policy: if_not_present
  
  db:
    # Используем docker.io с явным указанием + Alpine для уменьшения размера
    image: docker.io/library/postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - telegraph-network
    pull_policy: if_not_present

networks:
  telegraph-network:
    driver: bridge
volumes:
  postgres_data:
