version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - telegraph-network

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=cm804gz6c000u9mpmae
      - POSTGRES_PASSWORD=telegraphpass123
      - POSTGRES_DB=cm8048va00t0i9mpm8b0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - telegraph-network

networks:
  telegraph-network:
    driver: bridge

volumes:
  postgres_data:
