version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - telegraph-network
    pull_policy: if_not_present
  
  db:
    # Возвращаемся к PostgreSQL, но с явными значениями
    image: ghcr.io/cloudnative-pg/postgresql:14
    restart: always
    environment:
      - POSTGRES_USER=cm80dsv950015i9mpm20pa4fnt
      - POSTGRES_PASSWORD=cXlND3kctYXDJMudmUf6rmWYm
      - POSTGRES_DB=cm80dsv970017i9mpm0mwrf89d
      # Явное указание метода аутентификации
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - telegraph-network
    pull_policy: if_not_present

networks:
  telegraph-network:
    driver: bridge
volumes:
  postgres_data:
