version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_USER=cm804gz6c000u9mpmae
      - DB_HOST=db
      - DB_NAME=cm8048va00t0i9mpm8b0
      - DB_PASSWORD=telegraphpass123
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - telegraph-network

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=cm804gz6c000u9mpmae
      - POSTGRES_PASSWORD=telegraphpass123
      - POSTGRES_DB=cm8048va00t0i9mpm8b0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - telegraph-network

networks:
  telegraph-network:
    driver: bridge

volumes:
  postgres_data: